# Generated by Django 3.0.3 on 2020-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20200416_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_qty',
            field=models.IntegerField(default=None),
        ),
    ]
