# Generated by Django 3.0.3 on 2020-04-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20200417_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsubcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Admin.ItemCategory'),
        ),
    ]
