# Generated by Django 3.0.3 on 2020-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20200417_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
