# Generated by Django 3.0.3 on 2020-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20200417_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
